nodeLinker: node-modules

# yarnPath: .yarn/releases/yarn-3.6.4.cjs # This was suggested by react-native docs, but I'm using higher version
yarnPath: '/Users/derekchan/Desktop/Code/breakroom/.yarn/releases/yarn-berry.js'
